[package]
name = "t10"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.11.0"
tokio = { version = "1.40.0", features = ["time", "rt", "rt-multi-thread", "macros", "signal"] }
tokio-util = "0.7.12"