services:
  axum_server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: axum_server
    ports:
      - "3000:3000"
    env_file:
      - ./server/docker_compose.env
    depends_on:
      - postgres_db
    networks:
      - internal

  listener:
    build:
      context: .
      dockerfile: ./listener/Dockerfile
    container_name: listener
    env_file:
      - ./listener/docker_compose.env
    depends_on:
      - kafka
      - axum_server
    networks:
      - internal

  postgres_db:
    hostname: postgres
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - internal

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - internal

  kafka:
    hostname: kafka
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
    networks:
      - internal


networks:
  internal:
    driver: bridge