services:
  axum_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: axum_server
    ports:
      - "3000:3000"
    env_file:
      - ./docker_compose.env
    depends_on:
      - redis_db
    networks:
      - internal

  redis_db:
    hostname: redis
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - internal

networks:
  internal:
    driver: bridge