[package]
name = "t9"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = { version = "0.12.7", features = ["blocking"] }
